### PR TITLE
Lic7 8 9 fixes

### LINKED ISSUE #74: Fix: lic7,8,9
Add appropriate comments to the unit test, and methods for lic7, lic8 and lic 9

### PR DESCRIPTION
**Pull request by helinsaeid**
Added descriptive comments to each method and test. Also did some minor fixes to the limitations of some parameters used in the methods. Added additional tests so each method has one input test, one positive test and one negative test.

### CODE REVIEW

File: src/main/java/lab1/Decide.java [hunk 1]
```diff
@@ -342,9 +290,10 @@ public static boolean lic6() {
         return false;
     }
 
+    // Lic7 condition checks if the distance between two points with K_PTS intervening points inbetween is greater than the parameter LENGTH1 and returns true if it is
```
Comment (lizamaa123) [inline src/main/java/lab1/Decide.java]: you should add a title and then info of input and returns
e.g. :
 * LIC 7: ....
 * (your info you already have written)
 * Inputs: ....
 * Returns: ....

**Review by lizamaa123 — COMMENTED** [review]
Update the comments so it matches those committed to main branch :)
